# markdownlint (js library) config
heading-increment: false
no-inline-html: false
emphasis-style: false
first-line-h1: false
line-length: false
# MD029:
#   style: "ordered"
# MD007: false
# "MD007": { "indent": 4 }
# Checks anchor links, but insists on de-capitalization but that breaks links (tested in chrome)
link-fragments: false
