name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]
  schedule:
    - cron:  '0 9 * * MON'

permissions:
  contents: read

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"  # try to keep similar to Colab

    # Takes too long to run (>40min)
    # Could use docker instead? https://github.com/wsvn53/docker-colab-runtime-local
    # - name: Setup environment similar to Colab
    #   run: |
    #     python -m pip install --upgrade pip
    #     wget https://raw.githubusercontent.com/googlecolab/backend-info/main/pip-freeze.txt -O colab-freeze.txt
    #     cat colab-freeze.txt | grep -v '^#' | xargs -n 1 pip install  # 1-at-a-time ⇒ ignore errors

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests
      run: |
        tests/test_all.py
